version: "3"

services:
  db:
    container_name: hub_test_db
    image: postgres:11.4-alpine
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    container_name: hub_test_api
    build: ./api
    command: /bin/sh -c "rm -f /docker_hub_test/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/docker_hub_test
    depends_on:
      - db
      
  front:
    container_name: hub_test_front
    build: front/
    command: npm run dev
    volumes:
      - ./front:/app
    ports:
      - 8080:3000
    depends_on:
      - api
